<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB1CkUXz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB1CkUXz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB1CkUXz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB1CkUXz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB1CkUXz\App_KernelDevDebugContainer([
    'container.build_hash' => 'B1CkUXz',
    'container.build_id' => '13cd9c3f',
    'container.build_time' => 1731935352,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB1CkUXz');
